### ISSUE TITLE
X-509 format ServerPem

### ISSUE THREAD

**Issue by klinux** [gocd/gocd-vault-secret-plugin#39]
What is the string form that I need to put in ServerPem?

I'm trying a lot ways, but I always receive error:

Caused by: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input

Thank you

**Comment by etSpark** [comment]
From the readme.md, the input should be:
An X.509 certificate, in unencrypted PEM format with UTF-8 encoding to use when communicating with Vault over HTTPS

But I didn't get it work neither, if supplying the content of a pem file (-----BEGIN CERTIFICATE-----...----END CERTIFICATE-----) via UI to "ServerPem" in a Secrets Config
I obtain:

```
 ERROR [106@MessageListener for WorkFinder] Executor:127 - Failed to lookup secret from vault.
com.bettercloud.vault.VaultException: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Incomplete data
        at com.bettercloud.vault.SslConfig.buildSslContextFromPem(SslConfig.java:582)
        at com.bettercloud.vault.SslConfig.buildSsl(SslConfig.java:484)
        at com.bettercloud.vault.SslConfig.build(SslConfig.java:463)
        at com.thoughtworks.gocd.secretmanager.vault.builders.VaultConfigBuilder.configFrom(VaultConfigBuilder.java:32)
        at com.thoughtworks.gocd.secretmanager.vault.VaultProvider.vaultFor(VaultProvider.java:44)
        at com.thoughtworks.gocd.secretmanager.vault.SecretConfigLookupExecutor.execute(SecretConfigLookupExecutor.java:48)
        at com.thoughtworks.gocd.secretmanager.vault.SecretConfigLookupExecutor.execute(SecretConfigLookupExecutor.java:33)
        at cd.go.plugin.base.executors.secrets.LookupExecutor.execute(LookupExecutor.java:28)
        at cd.go.plugin.base.dispatcher.RequestDispatcher.lambda$dispatch$0(RequestDispatcher.java:41)
        at java.base/java.util.Optional.map(Unknown Source)
        at cd.go.plugin.base.dispatcher.RequestDispatcher.dispatch(RequestDispatcher.java:41)
        at com.thoughtworks.gocd.secretmanager.vault.VaultPlugin.handle(VaultPlugin.java:59)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
        at com.thoughtworks.go.plugin.access.secrets.v1.SecretsExtensionV1.lookupSecrets(SecretsExtensionV1.java:100)
        at com.thoughtworks.go.plugin.access.secrets.SecretsExtension.lookupSecrets(SecretsExtension.java:78)
        at com.thoughtworks.go.server.service.SecretParamResolver.lambda$lookupAndUpdateSecretParamsValue$1(SecretParamResolver.java:187)
        at java.base/java.util.HashMap.forEach(Unknown Source)
        at com.thoughtworks.go.server.service.SecretParamResolver.resolve(SecretParamResolver.java:178)
        at com.thoughtworks.go.server.service.SecretParamResolver.resolve(SecretParamResolver.java:126)
        at com.thoughtworks.go.server.service.BuildAssignmentService.buildEnvVarContext(BuildAssignmentService.java:356)
        at com.thoughtworks.go.server.service.BuildAssignmentService.lambda$createWork$2(BuildAssignmentService.java:307)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$execute$1(TransactionTemplate.java:31)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:28)
        at com.thoughtworks.go.server.service.BuildAssignmentService.lambda$createWork$3(BuildAssignmentService.java:302)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.transactionSurrounding(TransactionTemplate.java:60)
        at com.thoughtworks.go.server.service.BuildAssignmentService.createWork(BuildAssignmentService.java:286)
        at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:186)
        at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:165)
        at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:60)
        at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:32)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Incomplete data
        at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(Unknown Source)
        at java.base/java.security.cert.CertificateFactory.generateCertificate(Unknown Source)
        at com.bettercloud.vault.SslConfig.buildSslContextFromPem(SslConfig.java:543)
        ... 37 common frames omitted
Caused by: java.io.IOException: Incomplete data
        at java.base/sun.security.provider.X509Factory.readOneBlock(Unknown Source)
        ... 40 common frames omitted
```

If the "ServerPem" is provided via config.xml directly, I also always get the "Empty input"
(And if I don't supply "ServerPem" at all, I get an 403 response from the distant vault server (which can be accessed fine by the hc vault client on the same machine))

I'd like if the "ServerPem" attribute would expect to get the path to a .pem/.crt file passed. (which I also tried, resulted in: java.io.IOException: Empty Input)

Think I don't understand the readme:
An X.509 certificate, in unencrypted PEM format with UTF-8 encoding to use when communicating with Vault over HTTPS

pem certs are base64 encoded isn't it? So should I decode it with openssl x509 -in cert.pem -text --noout (probably not)

An example on how to correctly supply attribute "ServerPem" in the Secrets Config would be highly appreciated :)

**Comment by etSpark** [comment]
Update: think I got it work with the ServerPem

provide the certificate via gocd config xml
schema:
```
<property>
          <key>ServerPem</key>
          <Value>-----Start Certifcate-----
....
....
....
-----End Certificate-----</Value>
</property>
```
